### ISSUE TITLE
is it possible to use it without the CONNECT method?

### ISSUE THREAD

**Issue by unixfox** [Kolosok86/http-tls-proxy#7]
it seems like your program doesn't work in python because it doesn't use the CONNECT method when the request is sent in HTTP.

is there a way to make it support without the CONNECT method on the proxy?

thank you

**Comment by Kolosok86** [comment]
standard proxy requires CONNECT  method to be used, otherwise it's just an http server

**Comment by unixfox** [comment]
no when you send HTTP traffic, not HTTPS the HTTP library/client won't use CONNECT method.

I did test with python and curl, and your proxy was not working with them.

curl example command:
```
curl -x http://localhost:3128 ifconfig.co
```
